### ISSUE TITLE
How to use variable with ncbi

### ISSUE THREAD

**Issue by sahakyanhk** [PoisotLab/NCBITaxonomy.jl#58]
how to use a variable instead of "Lamellodiscus elegans" in
```
ncbi"Lamellodiscus elegans"
```

**Comment by tpoisot** [comment]
The `ncbi` bit in front is just a [non-standard string literal](https://docs.julialang.org/en/v1/manual/metaprogramming/#meta-non-standard-string-literals), and what it does in practice is call `taxon` with the default arguments: 

https://github.com/PoisotLab/NCBITaxonomy.jl/blob/2a3a84fe16e5d2f894d272bdba467528480303a1/src/taxon.jl#L108-L115

So you can get the same effect with

~~~julia
taxnamne = "Lamellodiscus ignoratus"
taxon(taxname)
~~~
